version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14.8-alpine3.17
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=admin
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data/:rw
    ports:
      - 5432:5432

  test_pgadmin:
    container_name: pgadmin_nn
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"

  web:
    container_name: django_nn
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./mysite:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A mysite worker --loglevel=info
    volumes:
      - ./mysite:/code
    links:
      - redis
    depends_on:
      - redis

  redis:
    container_name: redis_nn
    hostname: redis
    restart: always
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data