version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14.8-alpine3.17
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  test_pgadmin:
    container_name: test_pgadmin1
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=noemail@noemail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    